namespace RacketLite.Oporators
{
    public enum RacketOporatorType
    {
        //Special Oporators
        NOP,
        If,
        Local,
        Define,
        ReturnVariable,
        ReturnConstant,
        ReturnExpression,
        UserDefinedFunction,

        //Numeric Oporators
        Abs,
        Add,
        AddOne,
        ArcCosine,
        ArcSine,
        ArcTangent,
        Ceiling,
        Cosine,
        CurrentSeconds,
        Divide,
        Equal,
        Exponent,
        Exponential,
        Floor,
        GreaterThan,
        GreaterThanOrEqual,
        GreatestCommonDivisor,
        HyperbolicCosine,
        HyperbolicSine,
        IsEven,
        IsInteger,
        IsNatural,
        IsNegative,
        IsNumber,
        IsOdd,
        IsPositive,
        IsRational,
        IsZero,
        LessThan,
        LessThanOrEqual,
        LeastCommonMultiple,
        Maximum,
        Minimum,
        Modulo,
        Multiply,
        NaturalLog,
        Quotient,
        Random,
        Remainder,
        Round,
        Sign,
        Sine,
        Square,
        SquareRoot,
        Subtract,
        SubtractOne,
        Tangent,

        //Number Conversions
        ExactToInexact,
        InexactToExact,
        NumberToString,

        //Boolean Oporators
        And,
        BooleanEqual,
        IsBoolean,
        IsFalse,
        Not,
        Or,

        //Boolean Conversions
        BooleanToInteger,
        BooleanToString,

        //String Oporators
        StringLength,
        StringAppend,
        Substring,
        StringEqual,
        StringLessThan,
        StringGreaterThan,
        StringLessThanEqualTo,
        StringGreaterThanEqualTo,
    }
}